#!/bin/bash

FILES=`find . -name "grade_*.odt"`

for FILE in $FILES
do
  FNAME=`echo $FILE | cut -d '/' -f 3 | cut -d '.' -f 1`
  AUTHOR=`echo $FILE | cut -d '/' -f 2`

  libreoffice --headless --invisible --convert-to pdf $FILE
  mv ./$FNAME.pdf ./$AUTHOR-$FNAME.pdf
done

mkdir grades
mv *.pdf grades
